### ISSUE TITLE
Introducing Cbguard Breaks Coldbox invalidEventHandler Setting

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbguard#15]
The Coldbox `invalidEventHandler` setting allows us to create friendly 404 pages in our apps.  However, if you install cbguard in an app that uses `invalidEventHandler`, it will break the functionality and users will see the following exception error:  _"The invalidEventHandler setting is also invalid: error.onInvalidEvent. Please check your settings"_

For reference (and screenshots) I brought this issue up on [Google Groups](https://groups.google.com/forum/#!topic/coldbox/BZJtTbeiW7E) awhile back.

I've done my best to try and solve this problem on my own by closely following a request with an invalid event both with and without cbguard installed.   Even though I was not able to figure out how to fix the issue, I did learn a few things that might help.

First of all, I took a look at Coldbox's own handler service in `coldbox\system\web\services\HandlerService.cfc` and noticed that this error gets triggered when a global request variable, `request._lastInvalidEvent` matches the currently called event.  This was set up to initially prevent infinite loops.

What I figured out is that when cbguard is installed, the invalidEvent() method gets executed twice causing request._lastInvalidEvent to be set two times which makes the function think the invalidEventHandler is invalid.   I cannot figure out why cbguard triggers the HandlerService method twice.

**Steps to Reproduce:**
If you want to create a simple test setup to demonstrate the problem, create a blank coldbox app, and utilize the `invalidEventHandler` in your config.  Then, confirm that you can show a friendly 404 error when an invalid event gets called.   
Next, install cbsecurity and reinit your app.  You should see the problem occur.

**Comment by elpete** [comment]
Thank you for the detailed repro case.  I have found the issue and am now exploring potential fixes.

**Comment by homestar9** [comment]
Brilliant solution.  Thank you, Eric!

**Comment by elpete** [comment]
Released in [v4.1.1](https://github.com/coldbox-modules/cbguard/releases/tag/v4.1.1).
